# Generated by Django 4.2.5 on 2023-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
    ]
