# Generated by Django 4.2.5 on 2023-09-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0002_alter_projects_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachments",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MainApp.files"
                    ),
                ),
                (
                    "message_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MainApp.messages",
                    ),
                ),
            ],
        ),
    ]
