# Generated by Django 4.2.5 on 2023-09-13 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0003_messageattachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectComments",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_text", models.TextField()),
                (
                    "comment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MainApp.projects",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
