# Generated by Django 4.2.5 on 2023-09-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0006_alter_messageattachments_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachments",
            name="message_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MainApp.messages"
            ),
        ),
    ]
