# Generated by Django 4.2.5 on 2023-09-18 12:13

import MainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0008_alter_messageattachments_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=MainApp.models.user_avatar_path
            ),
        ),
    ]
