# Generated by Django 4.2.5 on 2023-09-18 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0010_users_last_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="last_activity",
        ),
    ]
