# Generated by Django 4.2.5 on 2023-09-18 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0011_remove_users_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 18, 12, 58, 19, 910047, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
