# Generated by Django 4.2.5 on 2023-09-21 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0012_users_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfiles",
            name="extension",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="MainApp.fileextensions",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectfiles",
            name="file_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="MainApp.filetypes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 21, 11, 6, 41, 756191, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
